/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.gateway.ctp.x64v6v3v16v.api;

public class CThostFtdcInvestUnitField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInvestUnitField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInvestUnitField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpv6v3v16x64apiJNI.delete_CThostFtdcInvestUnitField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestUnitID_get(swigCPtr, this);
  }

  public void setInvestorUnitName(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorUnitName_set(swigCPtr, this, value);
  }

  public String getInvestorUnitName() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorUnitName_get(swigCPtr, this);
  }

  public void setInvestorGroupID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorGroupID_set(swigCPtr, this, value);
  }

  public String getInvestorGroupID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_InvestorGroupID_get(swigCPtr, this);
  }

  public void setCommModelID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_CommModelID_set(swigCPtr, this, value);
  }

  public String getCommModelID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_CommModelID_get(swigCPtr, this);
  }

  public void setMarginModelID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_MarginModelID_set(swigCPtr, this, value);
  }

  public String getMarginModelID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_MarginModelID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_AccountID_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return jctpv6v3v16x64apiJNI.CThostFtdcInvestUnitField_CurrencyID_get(swigCPtr, this);
  }

  public CThostFtdcInvestUnitField() {
    this(jctpv6v3v16x64apiJNI.new_CThostFtdcInvestUnitField(), true);
  }

}
