/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.api.jctp.md;

public class CThostFtdcMarketDataField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcMarketDataField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcMarketDataField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpmdapiv6v3v11x64JNI.delete_CThostFtdcMarketDataField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_TradingDay_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ExchangeID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setLastPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LastPrice_set(swigCPtr, this, value);
  }

  public double getLastPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LastPrice_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setPreClosePrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreClosePrice_set(swigCPtr, this, value);
  }

  public double getPreClosePrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreClosePrice_get(swigCPtr, this);
  }

  public void setPreOpenInterest(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreOpenInterest_set(swigCPtr, this, value);
  }

  public double getPreOpenInterest() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreOpenInterest_get(swigCPtr, this);
  }

  public void setOpenPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_OpenPrice_set(swigCPtr, this, value);
  }

  public double getOpenPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_OpenPrice_get(swigCPtr, this);
  }

  public void setHighestPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_HighestPrice_set(swigCPtr, this, value);
  }

  public double getHighestPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_HighestPrice_get(swigCPtr, this);
  }

  public void setLowestPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LowestPrice_set(swigCPtr, this, value);
  }

  public double getLowestPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LowestPrice_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_Volume_get(swigCPtr, this);
  }

  public void setTurnover(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_Turnover_set(swigCPtr, this, value);
  }

  public double getTurnover() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_Turnover_get(swigCPtr, this);
  }

  public void setOpenInterest(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_OpenInterest_set(swigCPtr, this, value);
  }

  public double getOpenInterest() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_OpenInterest_get(swigCPtr, this);
  }

  public void setClosePrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ClosePrice_set(swigCPtr, this, value);
  }

  public double getClosePrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ClosePrice_get(swigCPtr, this);
  }

  public void setSettlementPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_SettlementPrice_set(swigCPtr, this, value);
  }

  public double getSettlementPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_SettlementPrice_get(swigCPtr, this);
  }

  public void setUpperLimitPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpperLimitPrice_set(swigCPtr, this, value);
  }

  public double getUpperLimitPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpperLimitPrice_get(swigCPtr, this);
  }

  public void setLowerLimitPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LowerLimitPrice_set(swigCPtr, this, value);
  }

  public double getLowerLimitPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_LowerLimitPrice_get(swigCPtr, this);
  }

  public void setPreDelta(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreDelta_set(swigCPtr, this, value);
  }

  public double getPreDelta() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_PreDelta_get(swigCPtr, this);
  }

  public void setCurrDelta(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_CurrDelta_set(swigCPtr, this, value);
  }

  public double getCurrDelta() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_CurrDelta_get(swigCPtr, this);
  }

  public void setUpdateTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpdateTime_set(swigCPtr, this, value);
  }

  public String getUpdateTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpdateTime_get(swigCPtr, this);
  }

  public void setUpdateMillisec(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpdateMillisec_set(swigCPtr, this, value);
  }

  public int getUpdateMillisec() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_UpdateMillisec_get(swigCPtr, this);
  }

  public void setActionDay(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ActionDay_set(swigCPtr, this, value);
  }

  public String getActionDay() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcMarketDataField_ActionDay_get(swigCPtr, this);
  }

  public CThostFtdcMarketDataField() {
    this(jctpmdapiv6v3v11x64JNI.new_CThostFtdcMarketDataField(), true);
  }

}
