# encoding: UTF-8

# 方向常量
DIRECTION_NONE = "NONE" # 无方向
DIRECTION_LONG = "LONG"  # 多
DIRECTION_SHORT = "SHORT"  # 空
DIRECTION_UNKNOWN = "UNKNOWN"  # 未知
DIRECTION_NET = "NET"  # 净
DIRECTION_SELL = "SELL"  # 卖出 IB
DIRECTION_COVEREDSHORT = "COVEREDSHORT"  # 备兑空 # 证券期权

# 开平常量
OFFSET_NONE = "NONE"  # 无开平
OFFSET_OPEN = "OPEN"  # 开仓
OFFSET_CLOSE = "CLOSE"  # 平仓
OFFSET_CLOSETODAY = "CLOSETODAY"  # 平今
OFFSET_CLOSEYESTERDAY = "CLOSEYESTERDAY"  # 平昨
OFFSET_UNKNOWN = "UNKNOWN"  # 未知

# 状态常量
STATUS_NOTTRADED = "NOTTRADED"  # 未成交
STATUS_PARTTRADED = "PARTTRADED"  # 部分成交
STATUS_ALLTRADED = "ALLTRADED"  # 全部成交
STATUS_CANCELLED = "CANCELLED"  # 已撤销
STATUS_REJECTED = "REJECTED"  # 拒单
STATUS_UNKNOWN = "UNKNOWN"  # 未知

STATUS_FINISHED = {
    STATUS_REJECTED,
    STATUS_CANCELLED,
    STATUS_ALLTRADED
}

STATUS_WORKING = {
    STATUS_UNKNOWN,
    STATUS_NOTTRADED,
    STATUS_PARTTRADED
}

# 合约类型常量
PRODUCT_EQUITY = "EQUITY"  # 股票
PRODUCT_FUTURES = "FUTURES"  # 期货
PRODUCT_OPTION = "OPTION"  # 期权
PRODUCT_INDEX = "INDEX"  # 指数
PRODUCT_COMBINATION = "COMBINATION"  # 组合
PRODUCT_FOREX = "FOREX"  # 外汇
PRODUCT_UNKNOWN = "UNKNOWN"  # 未知
PRODUCT_SPOT = "SPOT"  # 现货
PRODUCT_DEFER = "DEFER "  # 延期
PRODUCT_ETF = "ETF"  # ETF
PRODUCT_WARRANT = "WARRANT"  # 权证
PRODUCT_BOND = "BOND"  # 债券
PRODUCT_NONE = "NONE"  # NONE

# 价格类型常量
PRICETYPE_LIMITPRICE = "LIMITPRICE"  # 限价
PRICETYPE_MARKETPRICE = "MARKETPRICE "  # 市价
PRICETYPE_FAK = "FAK"  # FAK
PRICETYPE_FOK = "FOK"  # FOK

# 期权类型
OPTION_CALL = "CALL"  # 看涨期权
OPTION_PUT = "PUT"  # 看跌期权

# 交易所类型
EXCHANGE_SSE = "SSE"  # 上交所
EXCHANGE_SZSE = "SZSE"  # 深交所
EXCHANGE_CFFEX = "CFFEX"  # 中金所
EXCHANGE_SHFE = "SHFE"  # 上期所
EXCHANGE_CZCE = "CZCE"  # 郑商所
EXCHANGE_DCE = "DCE"  # 大商所
EXCHANGE_SGE = "SGE"  # 上金所
EXCHANGE_INE = "INE"  # 国际能源交易中心
EXCHANGE_UNKNOWN = "UNKNOWN" # 未知交易所
EXCHANGE_NONE = ""  # 空交易所
EXCHANGE_SEHK = "SEHK"  # 港交所
EXCHANGE_HKFE = "HKFE"  # 香港期货交易所

EXCHANGE_SMART = "SMART"  # IB智能路由（股票、期权）
EXCHANGE_NYMEX = "NYMEX"  # IB 期货
EXCHANGE_GLOBEX = "GLOBEX"  # CME电子交易平台
EXCHANGE_IDEALPRO = "IDEALPRO"  # IB外汇ECN

EXCHANGE_CME = "CME"  # 芝商所
EXCHANGE_ICE = "ICE"  # 洲际交易所
EXCHANGE_LME = "LME"  # 伦敦金属交易所

EXCHANGE_OANDA = "OANDA"  # OANDA外汇做市商
EXCHANGE_FXCM = "FXCM"  # FXCM外汇做市商

EXCHANGE_OKCOIN = "OKCOIN"  # OKCOIN比特币交易所
EXCHANGE_HUOBI = "HUOBI"  # 火币比特币交易所
EXCHANGE_LBANK = "LBANK"  # LBANK比特币交易所
EXCHANGE_KORBIT = "KORBIT"  # KORBIT韩国交易所
EXCHANGE_ZB = "ZB"  # 比特币中国比特币交易所
EXCHANGE_OKEX = "OKEX"  # OKEX比特币交易所
EXCHANGE_ZAIF = "ZAIF"  # ZAIF日本比特币交易所
EXCHANGE_COINCHECK = "COINCHECK"  # COINCHECK日本比特币交易所

# 货币类型
CURRENCY_USD = "USD"  # 美元
CURRENCY_CNY = "CNY"  # 人民币
CURRENCY_CNH = "CNH"  # 离岸人民币
CURRENCY_HKD = "HKD"  # 港币
CURRENCY_JPY = "JPY"  # 日元
CURRENCY_EUR = "EUR"  # 欧元
CURRENCY_GBP = "GBP"  # 英镑
CURRENCY_DEM = "DEM"  # 德国马克
CURRENCY_CHF = "CHF"  # 瑞士法郎
CURRENCY_FRF = "FRF"  # 法国法郎
CURRENCY_CAD = "CAD"  # 加拿大元
CURRENCY_AUD = "AUD"  # 澳大利亚元
CURRENCY_ATS = "ATS"  # 奥地利先令
CURRENCY_FIM = "FIM"  # 芬兰马克
CURRENCY_BEF = "BEF"  # 比利时法郎
CURRENCY_IEP = "IEP"  # 爱尔兰镑
CURRENCY_ITL = "ITL"  # 意大利里拉
CURRENCY_LUF = "LUF"  # 卢森堡法郎
CURRENCY_NLG = "NLG"  # 荷兰盾
CURRENCY_PTE = "PTE"  # 葡萄牙埃斯库多
CURRENCY_ESP = "ESP"  # 西班牙比塞塔
CURRENCY_IDR = "IDR"  # 印尼盾
CURRENCY_MYR = "MYR"  # 马来西亚林吉特
CURRENCY_NZD = "NZD"  # 新西兰元
CURRENCY_PHP = "PHP"  # 菲律宾比索
CURRENCY_SUR = "SUR"  # 俄罗斯卢布
CURRENCY_SGD = "SGD"  # 新加坡元
CURRENCY_KRW = "KRW"  # 韩国元
CURRENCY_THB = "THB"  # 泰铢

CURRENCY_UNKNOWN = "UNKNOWN"  # 未知货币
CURRENCY_NONE = ""  # 空货币

# 网关类型
GATEWAYTYPE_EQUITY = "equity"  # 股票、ETF、债券
GATEWAYTYPE_FUTURES = "futures"  # 期货、期权、贵金属
GATEWAYTYPE_INTERNATIONAL = "international"  # 外盘
GATEWAYTYPE_BTC = "btc"  # 比特币
GATEWAYTYPE_DATA = "data"  # 数据（非交易）