/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.api.jctp.md;

public class CThostFtdcQryBulletinField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQryBulletinField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQryBulletinField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpmdapiv6v3v11x64JNI.delete_CThostFtdcQryBulletinField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_ExchangeID_get(swigCPtr, this);
  }

  public void setBulletinID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_BulletinID_set(swigCPtr, this, value);
  }

  public int getBulletinID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_BulletinID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_SequenceNo_get(swigCPtr, this);
  }

  public void setNewsType(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_NewsType_set(swigCPtr, this, value);
  }

  public String getNewsType() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_NewsType_get(swigCPtr, this);
  }

  public void setNewsUrgency(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_NewsUrgency_set(swigCPtr, this, value);
  }

  public char getNewsUrgency() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcQryBulletinField_NewsUrgency_get(swigCPtr, this);
  }

  public CThostFtdcQryBulletinField() {
    this(jctpmdapiv6v3v11x64JNI.new_CThostFtdcQryBulletinField(), true);
  }

}
