/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.api.jctp.td;

public class CThostFtdcParkedOrderActionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcParkedOrderActionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcParkedOrderActionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctptraderapiv6v3v11x64JNI.delete_CThostFtdcParkedOrderActionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InvestorID_get(swigCPtr, this);
  }

  public void setOrderActionRef(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderActionRef_set(swigCPtr, this, value);
  }

  public int getOrderActionRef() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderActionRef_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderRef_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_RequestID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_SessionID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ExchangeID_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_OrderSysID_get(swigCPtr, this);
  }

  public void setActionFlag(char value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ActionFlag_set(swigCPtr, this, value);
  }

  public char getActionFlag() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ActionFlag_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_LimitPrice_get(swigCPtr, this);
  }

  public void setVolumeChange(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_VolumeChange_set(swigCPtr, this, value);
  }

  public int getVolumeChange() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_VolumeChange_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_UserID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InstrumentID_get(swigCPtr, this);
  }

  public void setParkedOrderActionID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ParkedOrderActionID_set(swigCPtr, this, value);
  }

  public String getParkedOrderActionID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ParkedOrderActionID_get(swigCPtr, this);
  }

  public void setUserType(char value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_UserType_set(swigCPtr, this, value);
  }

  public char getUserType() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_UserType_get(swigCPtr, this);
  }

  public void setStatus(char value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_Status_set(swigCPtr, this, value);
  }

  public char getStatus() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_Status_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_ErrorMsg_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_InvestUnitID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return jctptraderapiv6v3v11x64JNI.CThostFtdcParkedOrderActionField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcParkedOrderActionField() {
    this(jctptraderapiv6v3v11x64JNI.new_CThostFtdcParkedOrderActionField(), true);
  }

}
