/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.api.jctp;

public class CThostFtdcOrderField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcOrderField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcOrderField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpmdapiv6v3v11x64JNI.delete_CThostFtdcOrderField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InstrumentID_get(swigCPtr, this);
  }

  public void setOrderRef(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderRef_set(swigCPtr, this, value);
  }

  public String getOrderRef() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserID_get(swigCPtr, this);
  }

  public void setOrderPriceType(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderPriceType_set(swigCPtr, this, value);
  }

  public char getOrderPriceType() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderPriceType_get(swigCPtr, this);
  }

  public void setDirection(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_Direction_set(swigCPtr, this, value);
  }

  public char getDirection() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_Direction_get(swigCPtr, this);
  }

  public void setCombOffsetFlag(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CombOffsetFlag_set(swigCPtr, this, value);
  }

  public String getCombOffsetFlag() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CombOffsetFlag_get(swigCPtr, this);
  }

  public void setCombHedgeFlag(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CombHedgeFlag_set(swigCPtr, this, value);
  }

  public String getCombHedgeFlag() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CombHedgeFlag_get(swigCPtr, this);
  }

  public void setLimitPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_LimitPrice_set(swigCPtr, this, value);
  }

  public double getLimitPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_LimitPrice_get(swigCPtr, this);
  }

  public void setVolumeTotalOriginal(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTotalOriginal_set(swigCPtr, this, value);
  }

  public int getVolumeTotalOriginal() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTotalOriginal_get(swigCPtr, this);
  }

  public void setTimeCondition(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TimeCondition_set(swigCPtr, this, value);
  }

  public char getTimeCondition() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TimeCondition_get(swigCPtr, this);
  }

  public void setGTDDate(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_GTDDate_set(swigCPtr, this, value);
  }

  public String getGTDDate() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_GTDDate_get(swigCPtr, this);
  }

  public void setVolumeCondition(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeCondition_set(swigCPtr, this, value);
  }

  public char getVolumeCondition() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeCondition_get(swigCPtr, this);
  }

  public void setMinVolume(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_MinVolume_set(swigCPtr, this, value);
  }

  public int getMinVolume() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_MinVolume_get(swigCPtr, this);
  }

  public void setContingentCondition(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ContingentCondition_set(swigCPtr, this, value);
  }

  public char getContingentCondition() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ContingentCondition_get(swigCPtr, this);
  }

  public void setStopPrice(double value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_StopPrice_set(swigCPtr, this, value);
  }

  public double getStopPrice() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_StopPrice_get(swigCPtr, this);
  }

  public void setForceCloseReason(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ForceCloseReason_set(swigCPtr, this, value);
  }

  public char getForceCloseReason() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ForceCloseReason_get(swigCPtr, this);
  }

  public void setIsAutoSuspend(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IsAutoSuspend_set(swigCPtr, this, value);
  }

  public int getIsAutoSuspend() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IsAutoSuspend_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BusinessUnit_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_RequestID_get(swigCPtr, this);
  }

  public void setOrderLocalID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderLocalID_set(swigCPtr, this, value);
  }

  public String getOrderLocalID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InstallID_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_NotifySequence_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SettlementID_get(swigCPtr, this);
  }

  public void setOrderSysID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSysID_set(swigCPtr, this, value);
  }

  public String getOrderSysID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSysID_get(swigCPtr, this);
  }

  public void setOrderSource(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSource_set(swigCPtr, this, value);
  }

  public char getOrderSource() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderSource_get(swigCPtr, this);
  }

  public void setOrderStatus(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderStatus_set(swigCPtr, this, value);
  }

  public char getOrderStatus() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderStatus_get(swigCPtr, this);
  }

  public void setOrderType(char value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderType_set(swigCPtr, this, value);
  }

  public char getOrderType() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_OrderType_get(swigCPtr, this);
  }

  public void setVolumeTraded(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTraded_set(swigCPtr, this, value);
  }

  public int getVolumeTraded() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTraded_get(swigCPtr, this);
  }

  public void setVolumeTotal(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTotal_set(swigCPtr, this, value);
  }

  public int getVolumeTotal() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_VolumeTotal_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InsertTime_get(swigCPtr, this);
  }

  public void setActiveTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveTime_set(swigCPtr, this, value);
  }

  public String getActiveTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveTime_get(swigCPtr, this);
  }

  public void setSuspendTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SuspendTime_set(swigCPtr, this, value);
  }

  public String getSuspendTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SuspendTime_get(swigCPtr, this);
  }

  public void setUpdateTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UpdateTime_set(swigCPtr, this, value);
  }

  public String getUpdateTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UpdateTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CancelTime_get(swigCPtr, this);
  }

  public void setActiveTraderID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveTraderID_set(swigCPtr, this, value);
  }

  public String getActiveTraderID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveTraderID_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SequenceNo_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_SessionID_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserProductInfo_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_StatusMsg_get(swigCPtr, this);
  }

  public void setUserForceClose(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserForceClose_set(swigCPtr, this, value);
  }

  public int getUserForceClose() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_UserForceClose_get(swigCPtr, this);
  }

  public void setActiveUserID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveUserID_set(swigCPtr, this, value);
  }

  public String getActiveUserID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ActiveUserID_get(swigCPtr, this);
  }

  public void setBrokerOrderSeq(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BrokerOrderSeq_set(swigCPtr, this, value);
  }

  public int getBrokerOrderSeq() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BrokerOrderSeq_get(swigCPtr, this);
  }

  public void setRelativeOrderSysID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_RelativeOrderSysID_set(swigCPtr, this, value);
  }

  public String getRelativeOrderSysID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_RelativeOrderSysID_get(swigCPtr, this);
  }

  public void setZCETotalTradedVolume(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ZCETotalTradedVolume_set(swigCPtr, this, value);
  }

  public int getZCETotalTradedVolume() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_ZCETotalTradedVolume_get(swigCPtr, this);
  }

  public void setIsSwapOrder(int value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IsSwapOrder_set(swigCPtr, this, value);
  }

  public int getIsSwapOrder() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IsSwapOrder_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_BranchID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_InvestUnitID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_AccountID_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_CurrencyID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return jctpmdapiv6v3v11x64JNI.CThostFtdcOrderField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcOrderField() {
    this(jctpmdapiv6v3v11x64JNI.new_CThostFtdcOrderField(), true);
  }

}
