/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.gateway.ctp.x64v6v6v9v.api;

public class CThostFtdcQrySPBMFutureParameterField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQrySPBMFutureParameterField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQrySPBMFutureParameterField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpv6v6v9x64apiJNI.delete_CThostFtdcQrySPBMFutureParameterField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_ExchangeID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_InstrumentID_get(swigCPtr, this);
  }

  public void setProdFamilyCode(String value) {
    jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getProdFamilyCode() {
    return jctpv6v6v9x64apiJNI.CThostFtdcQrySPBMFutureParameterField_ProdFamilyCode_get(swigCPtr, this);
  }

  public CThostFtdcQrySPBMFutureParameterField() {
    this(jctpv6v6v9x64apiJNI.new_CThostFtdcQrySPBMFutureParameterField(), true);
  }

}
