/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package xyz.redtorch.gateway.ctp.x64v6v6v9cpv.api;

public class CThostFtdcInvestorProdSPBMDetailField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcInvestorProdSPBMDetailField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcInvestorProdSPBMDetailField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jctpv6v6v9cpx64apiJNI.delete_CThostFtdcInvestorProdSPBMDetailField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setExchangeID(String value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ExchangeID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_InvestorID_get(swigCPtr, this);
  }

  public void setProdFamilyCode(String value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ProdFamilyCode_set(swigCPtr, this, value);
  }

  public String getProdFamilyCode() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ProdFamilyCode_get(swigCPtr, this);
  }

  public void setIntraInstrMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_IntraInstrMargin_set(swigCPtr, this, value);
  }

  public double getIntraInstrMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_IntraInstrMargin_get(swigCPtr, this);
  }

  public void setBCollectingMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_BCollectingMargin_set(swigCPtr, this, value);
  }

  public double getBCollectingMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_BCollectingMargin_get(swigCPtr, this);
  }

  public void setSCollectingMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_SCollectingMargin_set(swigCPtr, this, value);
  }

  public double getSCollectingMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_SCollectingMargin_get(swigCPtr, this);
  }

  public void setIntraProdMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_IntraProdMargin_set(swigCPtr, this, value);
  }

  public double getIntraProdMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_IntraProdMargin_get(swigCPtr, this);
  }

  public void setNetMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_NetMargin_set(swigCPtr, this, value);
  }

  public double getNetMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_NetMargin_get(swigCPtr, this);
  }

  public void setInterProdMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_InterProdMargin_set(swigCPtr, this, value);
  }

  public double getInterProdMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_InterProdMargin_get(swigCPtr, this);
  }

  public void setSingleMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_SingleMargin_set(swigCPtr, this, value);
  }

  public double getSingleMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_SingleMargin_get(swigCPtr, this);
  }

  public void setAddOnMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_AddOnMargin_set(swigCPtr, this, value);
  }

  public double getAddOnMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_AddOnMargin_get(swigCPtr, this);
  }

  public void setDeliveryMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_DeliveryMargin_set(swigCPtr, this, value);
  }

  public double getDeliveryMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_DeliveryMargin_get(swigCPtr, this);
  }

  public void setCallOptionMinRisk(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_CallOptionMinRisk_set(swigCPtr, this, value);
  }

  public double getCallOptionMinRisk() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_CallOptionMinRisk_get(swigCPtr, this);
  }

  public void setPutOptionMinRisk(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_PutOptionMinRisk_set(swigCPtr, this, value);
  }

  public double getPutOptionMinRisk() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_PutOptionMinRisk_get(swigCPtr, this);
  }

  public void setOptionMinRisk(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionMinRisk_set(swigCPtr, this, value);
  }

  public double getOptionMinRisk() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionMinRisk_get(swigCPtr, this);
  }

  public void setOptionValueOffset(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionValueOffset_set(swigCPtr, this, value);
  }

  public double getOptionValueOffset() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionValueOffset_get(swigCPtr, this);
  }

  public void setOptionRoyalty(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionRoyalty_set(swigCPtr, this, value);
  }

  public double getOptionRoyalty() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_OptionRoyalty_get(swigCPtr, this);
  }

  public void setRealOptionValueOffset(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_RealOptionValueOffset_set(swigCPtr, this, value);
  }

  public double getRealOptionValueOffset() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_RealOptionValueOffset_get(swigCPtr, this);
  }

  public void setMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_Margin_set(swigCPtr, this, value);
  }

  public double getMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_Margin_get(swigCPtr, this);
  }

  public void setExchMargin(double value) {
    jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ExchMargin_set(swigCPtr, this, value);
  }

  public double getExchMargin() {
    return jctpv6v6v9cpx64apiJNI.CThostFtdcInvestorProdSPBMDetailField_ExchMargin_get(swigCPtr, this);
  }

  public CThostFtdcInvestorProdSPBMDetailField() {
    this(jctpv6v6v9cpx64apiJNI.new_CThostFtdcInvestorProdSPBMDetailField(), true);
  }

}
